SarSportApplicationBundle_application:
    resource: "@SarSportApplicationBundle/Resources/config/routing/application.xml"
    prefix:   /application

SarSportUserBundle:
    resource: "@SarSportUserBundle/Resources/config/routing.yml"
    prefix:   /

DefaultBundle:
    resource: "@DefaultBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /user-group

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

StfalconPaymentBundle:
    resource: "@StfalconPaymentBundle/Resources/config/routing/payment.xml"
    prefix:   /payment

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
